### ISSUE TITLE
You are not able to change the height / width of the grid

### ISSUE THREAD

**Issue by ludodv** [artsy-dev/Gallery#12]
**Reporter**: Prova
**Fixer**: ?
**Fixed version**: #?
You are not able to change the height / width of the grid.

**Expected Results**:
Be able to change the width/height of the grid.
**Actual Results**:
You always get a grid with the same height/width.
**Steps to Reproduce**:

1. Fill the width and height input
2. Press submit

**Comment by T99Rots** [comment]
Issue found and fixed.
Fixed in release: #14

**Comment by T99Rots** [comment]
Issue found and fixed.
Fixed in release: #14
