### ISSUE TITLE
Not all animations have a description

### ISSUE THREAD

**Issue by ludodv** [artsy-dev/Gallery#13]
**Reporter**: Prova
**Fixer**: ?
**Fixed version**: #?
Not all animations have a description.
**Expected Results**:
All animations have a description.
**Actual Results**:
When you select a certain animation you get an error.
**Steps to Reproduce**:

1. Select an animation
2. Hover over the description icon of an animation

**Comment by Lexouden** [comment]
Issue found and fixed.
**Fixed in release**: v1.0.1
